name: changeinventory
version: '${project.version}'
main: hakasenz.herteffect.ChangeInventory
api-version: 1.20
commands:
  ChangeInventory:
    usage: /changeinventory
  ChangeInventoryBuff:
    usage: /changeinventoryBuff